joo_global_object.__LIB__NODE__IMPORTS = {
  buffer: require("buffer"),
  childProcess: require("child_process"),
  console: require("console"),
  crypto: require("crypto"),
  dns: require("dns"),
  fs: require("fs"),
  fsPromises: require("fs").promises,
  http: require("http"),
  https: require("https"),
  net: require("net"),
  os: require("os"),
  path: require("path"),
  process: require("process"),
  stream: require("stream"),
  timers: require("timers"),
  tls: require("tls"),
  tty: require("tty"),
  util: require("util"),
};
